#!/usr/bin/env bash
#
# Generates test/test-schema.sql — a single consolidated snapshot of the fully
# migrated test database (Better Auth tables + all D1 migrations + the seed
# game version). Test setup applies this ONE file instead of replaying all
# ~248 migration files in every suite's beforeAll, which was the root cause of
# the vitest-pool-workers flake (massive per-suite storage churn racing the
# isolated-storage abort/refetch under WSL).
#
# ─────────────────────────────────────────────────────────────────────────────
# REGENERATE THIS WHENEVER YOU ADD OR CHANGE A MIGRATION:
#     npm run test:schema:gen
# The test run will FAIL FAST (vitest.config.ts guard) if the snapshot's baked
# migration count doesn't match src/db/migrations/ — that's your reminder.
# ─────────────────────────────────────────────────────────────────────────────
#
# Requires the sqlite3 CLI. Run under Linux/WSL (CI is Linux). Faithful because
# D1 is SQLite — the same engine the test pool uses.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MIG_DIR="$ROOT/src/db/migrations"
OUT="$ROOT/test/test-schema.sql"
WORK="$(mktemp -d)"
TMP="$WORK/schema.db"
COMBINED="$WORK/combined.sql"

# Build ONE combined script applied in a SINGLE sqlite3 session with
# foreign_keys=ON, so cascading deletes/rebuilds (e.g. migrations 0103/0104/0189
# touching vehicles) fire EXACTLY as they do in miniflare's FK-enforcing test
# pool. Per-file sqlite3 invocations each reset FK to off and diverge — that
# produced phantom orphaned rows (vehicle_images) the real test DB never has.
{
  echo "PRAGMA foreign_keys=ON;"
  # Better Auth core tables — MUST stay in sync with the schema Better Auth
  # creates at runtime. Migration 0004 ALTERs "user", so these exist first.
  echo 'CREATE TABLE IF NOT EXISTS "user" (id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, emailVerified INTEGER NOT NULL DEFAULT 0, image TEXT, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL, role TEXT DEFAULT '"'"'user'"'"', banned INTEGER DEFAULT 0, banReason TEXT, banExpires TEXT);'
  echo 'CREATE TABLE IF NOT EXISTS "session" (id TEXT PRIMARY KEY NOT NULL, expiresAt TEXT NOT NULL, token TEXT NOT NULL UNIQUE, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL, ipAddress TEXT, userAgent TEXT, userId TEXT NOT NULL REFERENCES "user"(id), impersonatedBy TEXT, activeOrganizationId TEXT);'
  echo 'CREATE TABLE IF NOT EXISTS "account" (id TEXT PRIMARY KEY NOT NULL, accountId TEXT NOT NULL, providerId TEXT NOT NULL, userId TEXT NOT NULL REFERENCES "user"(id), accessToken TEXT, refreshToken TEXT, idToken TEXT, accessTokenExpiresAt TEXT, refreshTokenExpiresAt TEXT, scope TEXT, password TEXT, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL);'
  echo 'CREATE TABLE IF NOT EXISTS "verification" (id TEXT PRIMARY KEY NOT NULL, identifier TEXT NOT NULL, value TEXT NOT NULL, expiresAt TEXT NOT NULL, createdAt TEXT, updatedAt TEXT);'
  echo 'CREATE TABLE IF NOT EXISTS "organization" (id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, logo TEXT, createdAt TEXT NOT NULL, metadata TEXT);'
  echo 'CREATE TABLE IF NOT EXISTS "member" (id TEXT PRIMARY KEY NOT NULL, organizationId TEXT NOT NULL REFERENCES "organization"(id), userId TEXT NOT NULL REFERENCES "user"(id), role TEXT NOT NULL DEFAULT '"'"'member'"'"', createdAt TEXT NOT NULL);'
  echo 'CREATE TABLE IF NOT EXISTS "invitation" (id TEXT PRIMARY KEY NOT NULL, organizationId TEXT NOT NULL REFERENCES "organization"(id), email TEXT NOT NULL, role TEXT, status TEXT NOT NULL DEFAULT '"'"'pending'"'"', expiresAt TEXT NOT NULL, inviterId TEXT NOT NULL REFERENCES "user"(id));'
  # All migrations in lexical order (matches readD1Migrations).
  COUNT=0
  for f in $(ls "$MIG_DIR"/*.sql | sort); do
    echo "-- >>> $(basename "$f")"
    cat "$f"
    echo ""
    COUNT=$((COUNT + 1))
  done
  # Seed the default test game version (TEST_GAME_VERSION_ID relies on it).
  echo "INSERT OR IGNORE INTO game_versions (uuid, code, channel, is_default, released_at) VALUES ('test-0000-0000-0000-000000000001', '4.0.0-test', 'LIVE', 1, '2026-01-01');"
  echo "-- migration-count: $COUNT"
} > "$COMBINED"
COUNT=$(grep -c '^-- >>> ' "$COMBINED")

# Apply the whole thing in one FK-enforcing session.
sqlite3 "$TMP" ".read $COMBINED"

# Emit in apply-safe order: ALL CREATE TABLE, then ALL CREATE INDEX, then ALL
# data INSERTs. miniflare enforces foreign keys and ignores PRAGMA foreign_keys
# = OFF, so every FK-target table must exist before any INSERT runs (else "no
# such table") and the data must be FK-clean (it is — generated above with FK
# ON, so cascade deletes already removed orphans). sqlite_sequence (internal),
# d1_migrations (bookkeeping) and autoindexes are excluded.
{
  echo "-- AUTO-GENERATED by test/generate-test-schema.sh — DO NOT EDIT BY HAND."
  echo "-- Consolidated test DB baseline (Better Auth + migrations + seed)."
  echo "-- migrations: $COUNT"
  echo "-- Regenerate after adding/changing a migration: npm run test:schema:gen"
  echo "-- ── tables ──"
  sqlite3 "$TMP" "SELECT sql || ';' FROM sqlite_master WHERE type='table' AND sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name <> 'd1_migrations' ORDER BY rowid;"
  echo "-- ── indexes ──"
  sqlite3 "$TMP" "SELECT sql || ';' FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY rowid;"
  echo "-- ── data ──"
  # Exclude vehicle_images / vehicle_images_archive seed rows: they are ORPHANS
  # (vehicle_id → a vehicles row that a later migration DROP-recreated away).
  # They were inserted validly mid-sequence then orphaned by the DROP, so a flat
  # replay can't recreate them under miniflare's (PRAGMA-ignoring) FK enforcement
  # — the INSERT fails FOREIGN KEY. No test reads the seed rows; the few tests
  # that need vehicle_images insert their own for vehicles they create.
  sqlite3 "$TMP" .dump \
    | grep -E '^INSERT INTO' \
    | grep -ivE '^INSERT INTO "?sqlite_sequence"?' \
    | grep -vE '^INSERT INTO "?d1_migrations"?' \
    | grep -vE '^INSERT INTO "?vehicle_images(_archive)?"? '
} > "$OUT"

echo "Wrote $OUT  ($COUNT migrations, $(wc -l < "$OUT") lines, $(grep -c '^CREATE TABLE' "$OUT") tables, $(grep -c '^INSERT INTO' "$OUT") seed rows)"
